version: '3.8'
services:
  database:
    build: ./neo4j
    ports:
    - "7474:7474"
    - "7687:7687"
    volumes:
    - $HOME/neo4j-ce/data:/data
    environment:
      - NEO4J_AUTH=neo4j/secret

  backend-api:
    build: ./backend-api
    ports:
      - "8080:8080"
    environment:
      - DB_ENDPOINT=bolt://database:7687
      - DB_USERNAME=neo4j
      - DB_PASSWORD=secret
      - SPRING_PROFILES_ACTIVE=docker